-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) YEAR, 
        (b.mx_size - SIZE_OF_COLONY) YEAR_DEV, ID
FROM (
    SELECT *, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA) a
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR,
    MAX(SIZE_OF_COLONY) mx_size
FROM ECOLI_DATA
GROUP BY YEAR) b
ON A.YEAR = B.YEAR
ORDER BY 1, 2