-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (SELECT BOOK_ID, SALES FROM BOOK_SALES WHERE SALES_DATE LIKE "%2022-01%") AS S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY ASC